on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v5

  publish:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: actions/setup
        uses: ./.github/actions/setup
      - run: npm publish --provenance --tag latest
